export { default as About } from './About'
export { default as Contact } from './Contact'
export { default as Hero } from './Hero'
export { default as Niches } from './Niches'
export { default as Parallax } from './Parallax'
